name: newx-prisma-mysql
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    ports:
      - 3000:3000
    volumes:
      - ../:/app
      - ../.env.development:/app/.env
      - node_modules:/app/node_modules
      - next:/app/.next

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ../.env.development
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  node_modules:
  next:
